TT=tabmaker9000.cc
EE=funzioni.h
BB=tabslayer
CC=tebellinator.cc
AA=funzioni2.0.h
MM=trombelle

#$(BB): $(TT) $(EE)
#	g++ -o $(BB) $(TT)

$(MM): $(CC) $(AA)
	g++ -o $(MM) $(CC)

run:
	./$(MM)

clean:
	rm $(BB)
